# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='submissions_count',
            field=models.IntegerField(default=0),
        ),
    ]
