# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-19 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='messages_count',
            field=models.IntegerField(default=0),
        ),
    ]
