# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='object_id',
        ),
    ]
