# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_remove_category_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='author',
        ),
    ]
